services:

  api:
    image: ubuntu:latest
    ports:
      - "5252:5252"
    build:
      context: ./back-end
      dockerfile: Dockerfile

  nginx:
    image: nginx:latest
    ports:
      - "9000:9000"
    build:
      context: ./front-end
      dockerfile: Dockerfile
    depends_on:
      - api
